### ISSUE TITLE
Output

### ISSUE THREAD

**Issue by mattsodoma** [HBClab/SnapMaze#2]
Output is collecting only the last trial of both conditions (wayfinding and route following). It is not collecting learning trials or test trials before the last one.  Tested with partial sessions and is not recording.

Ideal scenario:
Collects  data for 4 learning trials for wayfinding determined by time (5 min)
Collects subset trial data for 4 learning trials of route learning determined by time (5 min), but will likely complete the route multiple times witihin the 5 minute time

Collects data for 12 testing trials of wayfinding
Collects data for 3 route following test trials

**Comment by mattsodoma** [comment]
[sub-matttest_4.xlsx](https://github.com/HBClab/SnapMaze/files/1848963/sub-matttest_4.xlsx)

**Comment by mattsodoma** [comment]
Trials seem to be outputting correctly, might be something odd going on in the calculations for total distance and velocity (example subtrial 2 - movement time for subtrial was only 2 seconds for learning cause i lowered the total time to 60 seconds)  but it has the total distance being 5800 which means I wouldve gone another 2800 units on top of the 3000ish I did in 58 seconds.

**Comment by mattsodoma** [comment]
@jdkent in regards to your question, partial trials record information now as well (i.e. if you quit before the program makes you quit).

**Comment by jdkent** [comment]
You should open the distance/velocity problem as another issue (unless it only started happening when I made these changes). I don't think I changed any of the code that would influence that calculation, but i could be wrong.

**Comment by mattsodoma** [comment]
Yeah you're right, I looked back on some of the pilot data and it is present in the learning trials so doesn't seem to be related to the code you wrote... I opened a new issue. Its almost like its calculating the distance from the endpoint of previous trial to startpoint of next trial from birds eye perspective.
