### ISSUE TITLE
Existing file error

### ISSUE THREAD

**Issue by mattsodoma** [HBClab/SnapMaze#5]
Error in creating an output file when the subject name already exists.  Confirmed new subject ID's work correctly after trying every maze with same subject ID and repeating the error.
![mace c wayfinding error](https://user-images.githubusercontent.com/34074845/38275335-2ba07f28-3757-11e8-8969-97a4736ec9b7.jpg)
![maze b wayfinding test](https://user-images.githubusercontent.com/34074845/38275336-2bb7680a-3757-11e8-9745-afd2eb62869c.jpg)

**Comment by jdkent** [comment]
Let me know if the fix doesn't work, you can test with downloading the branch `coordColumns`

**Comment by mattsodoma** [comment]
Initial testing - everything seems to be working. Will have undergrads do more extensive testing and reopen issue if it shows back up.
